version: '3.8'

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: frontend-front
    image: leenominai/frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    container_name: foodgram-app
    image: leenominai/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
