# Generated by Django 2.2.16 on 2023-06-05 20:40

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Введите описание рецепта', unique=True, validators=[recipes.validators.validate_text], verbose_name='Описание рецепта'),
        ),
    ]
