# Generated by Django 2.2.16 on 2023-06-01 07:01

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите своё имя', max_length=150, validators=[users.validators.validate_names], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите свою фамилию', max_length=150, validators=[users.validators.validate_names], verbose_name='Фамилия'),
        ),
    ]
